version: "2"
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    # - whitespace
  settings:
    lll:
      line-length: 140
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "10"
      ignored-functions:
        - strings.SplitN
    goconst:
      min-len: 2
      min-occurrences: 3
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    presets:
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - mnd
          - funlen
      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - goimports
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # new-from-rev: origin/master
  exclude:
    - "should have comment"
    - "always receives"
    - "should not use underscores in package names"
    - "parameter .* is always"
    - "comment on exported .* should be of the form"
    - "Use of weak cryptographic primitive"
    - "can be `fmt.Stringer`"
    - "can be `github.com/gogo/protobuf/proto.Message`"
    - 'ST1016: methods on the same type should have the same receiver name \(seen \d+x "[^"]+", 4x "v"\)'
    - 'ST1016: methods on the same type should have the same receiver name \(seen 4x "v", \d+x "[^"]+"\)'
    - 'ST1016: methods on the same type should have the same receiver name \(seen \d+x "[^"]+", \d+x "srv"\)'
    - 'ST1016: methods on the same type should have the same receiver name \(seen \d+x "srv", \d+x "[^"]+"\)'
    - '\.MarshalJSON - result 1 \(error\) is always nil'
    - '\.Value - result 1 \(error\) is always nil'
    - '\.Directive` - .* is unused'
  # Excluding configuration per-path, per-linter, per-text and per-source
